# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  
  desc "Build IOS App"
  lane :build_release_ios do
    # match
    gym(
      workspace: "ios/arkflow.xcworkspace",
      configuration: "Release",
      scheme: "arkflow",
      export_options: {
        method: "ad-hoc",
        # method: "app-store",
        signingStyle: "automatic",
        provisioningProfiles: {
          "com.ark.deglory.arkflow" => "match AdHoc com.ark.deglory.arkflow",
          # "com.ark.deglory.arkflow" => "match AppStore com.ark.deglory.arkflow",
        }
      }
    )
    # deliver(
    #   verify_only: true,
    #   # submit_for_review: true,
    #   force: true,  # Skip HTMl report verification
    #   username: "newwavehotel@gmail.com",
    #   app_identifier: "com.ark.deglory.arkflow",
    #   ipa: "arkflow.ipa",
    #   #skip_binary_upload: true, # upload ipa
    #   skip_screenshots: true,
    #   skip_metadata: true
    # )
  end
end

platform :android do
  
  desc "Build android apk"
  lane :build_release_android do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android/'
    )
  end

  desc "Build android aab"
  lane :build_bundle_android do
    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'android/'
    )
  end
end