# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  desc "Build android apk"
  lane :build_release_android do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android/'
    )
  end
end

default_platform(:ios)

platform :ios do
  
  desc "Build IOS App"
  lane :build_release_ios do
    # match
    gym(
      workspace: "ios/arkflow.xcworkspace",
      configuration: "Release",
      scheme: "arkflow",
      export_options: {
        method: "ad-hoc",
        signingStyle: "automatic",
        provisioningProfiles: {
          "com.ark.deglory.arkflow" => "match AdHoc com.ark.deglory.arkflow",
        }
      }
    )
  end
end