# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  
  desc "Build IOS App"
  lane :archive_ios do
    gym(
      workspace: "ios/arkflow.xcworkspace",
      configuration: "Release",
      scheme: "arkflow",
      export_options: {
        # method: "ad-hoc",
        method: "app-store",
        signingStyle: "automatic",
        provisioningProfiles: {
          # "com.ark.deglory.arkflow" => "match AdHoc com.ark.deglory.arkflow",
          "com.ark.deglory.arkflow" => "match AppStore com.ark.deglory.arkflow",
        }
      }
    )
  end

  desc "Upload to testflghit"
  lane :upload_ipa_to_testflight do |options|
    upload_to_testflight(
      username: "newwavehotel@gmail.com",
      app_identifier: "com.ark.deglory.arkflow"
    )
  end

  desc "Submit_for review"
  lane :submit_for_review do |options|
    deliver(
      # verify_only: true,  #Verifies archive without uploading
      submit_for_review: true,
      automatic_release: true,
      force: true,  # Skip HTMl report verification
      username: "newwavehotel@gmail.com",
      app_identifier: "com.ark.deglory.arkflow",
      ipa: "arkflow.ipa",
      #skip_binary_upload: true, # if only upload screenshot or metadata without ipa
      skip_screenshots: true,
      skip_metadata: true,
      # metadata_path: "./metadata"
      # reject_if_possible: true, #Rejects the previously submitted build if it's in a state where it's possible (before it was approved)
    )
  end

  desc "Build and Distribute to testflghit"
  lane :release_new_version do |options|
    # match
    archive_ios options
    upload_ipa_to_testflight
    # submit_for_review
  end
end

platform :android do
  
  desc "Build android apk"
  lane :build_release_android do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android/'
    )
  end

  desc "Build android aab"
  lane :build_bundle_android do
    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'android/'
    )
  end

  lane :upload_to_playstore do
    upload_to_play_store(
      aab: "android/app/build/outputs/bundle/release/app-release.aab",
      track: 'internal', # production
    )
  end

  lane :release_new_version_play_store do |options|
    # build_bundle_android
    upload_to_playstore
  end
end